# Generated by Django 5.1.4 on 2024-12-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Format-specific metadata. Structure varies by capture_type.'),
        ),
    ]
