# Generated by Django 5.1.4 on 2024-12-15 00:45

import captures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_alter_capture_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacapture',
            name='file',
            field=models.FileField(max_length=500, upload_to=captures.models.get_upload_path),
        ),
    ]
